AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bot for finding saved voice messages

Globals:
  Function:
    Timeout: 15

Resources:
  FindMyVoiceBotHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handle_bot_message/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HandleBotMessage:
          Type: Api
          Properties:
            Path: /handle_bot_message
            Method: post

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FindMyVoiceApi:
    Description: "API Gateway endpoint URL for Prod stage for FindMyVoiceBotHandler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/handle_bot_message/"
  FindMyVoiceFunction:
    Description: "FindMyVoiceBotHandler Lambda Function ARN"
    Value: !GetAtt FindMyVoiceBotHandler.Arn
  FindMyVoiceFunctionIamRole:
    Description: "Implicit IAM Role created for FindMyVoiceBotHandler function"
    Value: !GetAtt FindMyVoiceBotHandlerRole.Arn
